---
r1:
    hostname: 192.168.254.128
    port: 5012
    username: 
    password: cisco
    platform: ios
    groups:
        - r1_grp
    data:
        site: home
        role: cisco
        type: router
    connection_options:
        napalm:
            extras:
                optional_args: {
                    transport: 'telnet', 
                    # global_delay_factor: 2,
                    secret: 'cisco',
                    # dest_file_system: 'ios' # required for napalm_configure
                    }
        netmiko:
          extras:
              device_type: 'cisco_ios_telnet'